paths:
  /pets:
    get:
      summary: List all values
      operationId: listValues
      tags:
        - values
      responses:
        "200":
          description: An array of values
          schema:
            $ref: '#/definitions/Value'
    post:
      summary: Create a value
      operationId: createValues
      tags:
        - values
      responses:
        "201":
          description: Null response

  /pets/{id}:
    get:
      summary: Info for a specific value
      operationId: showValueById
      tags:
        - values
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the value to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Value'
